### PR TITLE
Test and fix for allowing services with only a setup method

### LINKED ISSUE #285: Cryptic error message on "setup-only" service.
Just noticed if you create a service with only a Service#setup(...) function and `app.use(...)` it. 
You get a cryptic error message ( my guess - it's coming from express ), "Router.use() requires middleware function but got a Object".

Example:
```
// Error
const SomeService = {
	setup(app, path) {}
}
​
// No Error
​
const AnoterService = {
	setup(app, path) {},
	create(data, params, cb) {}
}
​
​
app.use('/some', SomeService); // cryptic error
app.use('/another', AnotherService); // Fine
```

### PR DESCRIPTION
**Pull request by daffl**
Closes #285

### CODE REVIEW

File: src/application.js [hunk 1]
```diff
@@ -75,10 +76,11 @@ export default {
       });
 
     const hasMethod = methods => methods.some(name =>
-      (service && typeof service[name] === 'function'));
+      (service && typeof service[name] === 'function')
+    );
 
     // Check for service (any object with at least one service method)
-    if(hasMethod(['handle', 'set']) || !hasMethod(this.methods)) {
+    if(hasMethod(['handle', 'set']) || !hasMethod(this.methods.concat('setup'))) {
```
Comment (ekryski) [inline src/application.js]: Do we want to throw an error or a debug warning in case the service doesn't have a `setup` method?

File: test/application.test.js [hunk 2]
```diff
@@ -326,6 +326,20 @@ describe('Feathers application', () => {
     assert.equal(otherApp.mixins.length, 4);
   });
 
+  it('setup only services work (#285)', done => {
```
Comment (ekryski) [inline test/application.test.js]: I don't really know what this means? Maybe we can rephrase to "initializes a service with only a setup method"?

File: src/application.js (hunk 1 above)
Comment (daffl) [inline src/application.js]: What do you mean? Services without a `setup` method shouldn't be a problem.

Comment (ekryski) [inline src/application.js]: After I made that comment I realized it didn't make sense. PROCEED! 😄

**Comment by ekryski** [comment]
:shipit:
